/**
 * Newsreader Backend API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package nl.greimel.fabian.model

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param feed 
 * @param title 
 * @param summary 
 * @param publishDate 
 * @param image 
 * @param url 
 * @param related 
 * @param categories 
 * @param isLiked 
 */

data class Article (

    @Json(name = "Id")
    val id: kotlin.Int? = null,

    @Json(name = "Feed")
    val feed: kotlin.Int? = null,

    @Json(name = "Title")
    val title: kotlin.String? = null,

    @Json(name = "Summary")
    val summary: kotlin.String? = null,

    @Json(name = "PublishDate")
    val publishDate: kotlin.String? = null,

    @Json(name = "Image")
    val image: kotlin.String? = null,

    @Json(name = "Url")
    val url: kotlin.String? = null,

    @Json(name = "Related")
    val related: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "Categories")
    val categories: kotlin.collections.List<Category>? = null,

    @Json(name = "IsLiked")
    val isLiked: kotlin.Boolean? = null

)

