/**
 * Newsreader Backend API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package nl.greimel.fabian.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param authToken 
 */

data class LoginResponse (

    @Json(name = "AuthToken")
    val authToken: kotlin.String? = null

)

