/**
 * Newsreader Backend API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package nl.greimel.fabian.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param success 
 * @param message 
 */

data class RegisterResponse (

    @Json(name = "Success")
    val success: kotlin.Boolean? = null,

    @Json(name = "Message")
    val message: kotlin.String? = null

)

